# Site settings
<<<<<<< HEAD
title: Williams Paleo Lab
email: your-email@domain.com
url: https://example.github.io
description: This is Williams Paleo Lab.
=======
title: Williams Lab
email: jwwilliams1@wisc.edu
url: https://example.github.io
description: "Paleoecology - Paleoclimatology - Global Climate Change - Quaternary Environments."
>>>>>>> d7e0cbee3e3e5a2c4b1ad5cee59e3a8b79a4549a

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Williams Paleo Lab

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty

##People
collections:
  people:
    output: true
    permalink: /people/:path/
